#THIS IS SAMPLE FILE
#Copy its content to config.yml file
#It is used only when you run tests using IDE

browser: FF #acceptable values: FF, CHROME, GHOST, ANDROID, CHROMEMOBILE, CHROMEMOBILEMERCURY
wikiName: mediawiki119 #default testing wiki
env: prod #acceptable values: prod, preview, sandbox-number dev-name
credentialsPath: /selenium-config/config.xml #Path to your config.xml file
captchaPath: /selenium-config/captcha.txt #Path to your captcha.txt file
qs: null
disableFlash: true
jsErrorsEnabled: false
logEnabled: true

#Config related with mobile devices
platform: ANDROID #acceptable values: IOS and ANDROID
platformVersion: null #Example: 4.4 for Android 4.4
deviceId: null #For Android devices uuid (can be obtained by running adb devices)
mobileConfig:  #Path to your mobile-config.xml file
appiumIp: 127.0.0.1:4723 #Appium IP address with port ex. 127.0.0.1:4723 Windows 0.0.0.0:4723 Unix
deviceName: ANDROID #capability for Appium server. For Android it can be any value.
