# THIS IS A DEFAULT CONFIGURATION
# To localy override values, create config.yml file next to this one.
# You can also override these values by specyfing a system property

browser: FF # acceptable values: FF, CHROME, GHOST, ANDROID, CHROMEMOBILEMERCURY, HTMLUNIT
wikiName: mediawiki119 # default testing wiki
env: prod # acceptable values: prod, preview, sandbox-number dev-name
credentialsPath: /selenium-config/config.xml # Path to your config.xml file
captchaPath: /selenium-config/captcha.txt # Path to your captcha.txt file
qs: null
disableFlash: true
jsErrorsEnabled: false
logEnabled: true
takeScreenshots: true
mockAds: false
disableCommunityPageSalesPitchDialog: true
useMITM: false
useZapProxy: false

# Specify browser window size in format <width>x<height>, example: 800x600
# use "maximised" value if you want browser to be maximised
browserSize: maximised

# Add browser extensions.
# Acceptable values:
# for CHROME: adblock, adblock+, ublock
# for FF: adblock+, JSErrorCollector
extensions: null

# Run on emulated device
# Example: Google Nexus 5
emulator: null

# Config related with mobile devices
platform: ANDROID # acceptable values: IOS and ANDROID
appiumIp: 127.0.0.1:4723 # Appium IP address with port ex. 127.0.0.1:4723 Windows 0.0.0.0:4723 Unix
deviceName: ANDROID # capability for Appium server. For Android it can be any value.
